// Stage M3 report (docs/staging/em-prereg.md §M3): the focal animals in the arms R (rules), A (the loop with the rules'
// argmax), G (the loop with a GLiNER provider) and, iteration 2, AG and GG (the same with RG's gate: the provider replaces
// RG's draws only), from scripts/em-loop.ts outputs (s<seed>-RA, -G, -AG, -GG); field rows from data/targets.json.
//
//   pnpm exec tsx scripts/em-loop-report.ts [--dir artifacts/em/m3] [--seeds 48,7]
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const arg = (k: string, d: string) => { const i = process.argv.indexOf(`--${k}`); return i > 0 ? process.argv[i + 1] : d; };
const dir = resolve(arg('dir', 'artifacts/em/m3')), seeds = arg('seeds', '48,7').split(',').map(Number);
const targets = (JSON.parse(readFileSync(resolve('data/targets.json'), 'utf8')) as { targets: { id: string; accept: { lo: number; hi: number } }[] }).targets;
const band = (id: string) => targets.find(t => t.id === id)!.accept;
type Row = { id: number; name: string; cls: string; alive: boolean; cause: string | null; share: Record<string, number | null>; restOrGroom: number | null; feedMinPerDay: number;
  kcalPerDay: number; reservePctPerDay: number; pathKmPerDay: number; fixPathKmPerDay: number; nightOutPct: number | null; decisions: number; applied: number;
  fallbacks: Record<string, number>; rulesAgree: number | null; picks: Record<string, number>; rulesPicks: Record<string, number> };
type Arm = { arm: string; provider: string; days: number; seconds: number; modelSeconds: number; calls: number; deaths: { id: number; cause: string | null }[]; focal: Row[] };
const load = (f: string) => existsSync(f) ? JSON.parse(readFileSync(f, 'utf8')) as { burnInHash: string; results: Arm[] } : null;

const ROWS: [string, string, (r: Row) => number | null, (r: Row) => boolean][] = [
  ['T-ACT-1 feeding', 'T-ACT-1', r => r.share.feed, () => true],
  ['T-ACT-2 travel', 'T-ACT-2', r => r.share.travel, () => true],
  ['T-ACT-3 grooming', 'T-ACT-3', r => r.share.groom, () => true],
  ['T-ACT-4 rest + groom', 'T-ACT-4', r => r.restOrGroom, () => true],
  ['T-RNG-4 day range (5-min fixes)', 'T-RNG-4', r => r.fixPathKmPerDay, r => r.cls.startsWith('adult male')],
  ['T-ENE-2 feeding min/day', 'T-ENE-2', r => r.feedMinPerDay, r => r.cls === 'female, lactating'],
];
const md: string[] = ['# M3 report (generated by scripts/em-loop-report.ts)', ''];
const inBand: Record<string, [number, number]> = {};
const means: Record<string, Row[]> = {};
const f2 = (v: number | null | undefined) => v === null || v === undefined || !Number.isFinite(v) ? '–' : v.toFixed(2);
for (const seed of seeds) {
  const ra = load(join(dir, `s${seed}-RA.json`)), g = load(join(dir, `s${seed}-G.json`)), ag = load(join(dir, `s${seed}-AG.json`)), gg = load(join(dir, `s${seed}-GG.json`));
  if (!ra) continue;
  for (const [n, f] of [['G', g], ['AG', ag], ['GG', gg]] as const) if (f && f.burnInHash !== ra.burnInHash) throw new Error(`seed ${seed}: ${n}'s burn-in differs from R/A's`);
  const arms: [string, Arm | undefined][] = [['R', ra.results.find(a => a.arm === 'rules')], ['A', ra.results.find(a => a.arm === 'model')], ['G', g?.results.find(a => a.arm === 'model')],
    ['AG', ag?.results.find(a => a.arm === 'model')], ['GG', gg?.results.find(a => a.arm === 'model')]];
  md.push(`## Seed ${seed} (${arms.filter(a => a[1]).map(([n, a]) => `${n}: ${a!.provider}, ${a!.days} d, ${a!.seconds} s${a!.calls ? `, ${a!.calls} calls` : ''}`).join('; ')})`, '');
  md.push('| animal | arm | feed | travel | groom | rest+groom | feed min/d | kcal/d | reserve %/d | km/d (fixes) | km/d (ticks) | night out % | alive | decisions (rules agree; fallbacks) |', '|---|---|---|---|---|---|---|---|---|---|---|---|---|---|');
  const focal = arms[0][1]!.focal;
  for (const f of focal) for (const [name, a] of arms) {
    if (!a) continue;
    const r = a.focal.find(x => x.id === f.id)!;
    (means[name] ??= []).push(r);
    const fb = Object.entries(r.fallbacks).map(([k, v]) => `${k} ${v}`).join(', ');
    md.push(`| ${f.name} (${f.cls}) | ${name} | ${f2(r.share.feed)} | ${f2(r.share.travel)} | ${f2(r.share.groom)} | ${f2(r.restOrGroom)} | ${r.feedMinPerDay.toFixed(0)} | ${r.kcalPerDay} | ${r.reservePctPerDay.toFixed(3)} | ${f2(r.fixPathKmPerDay)} | ${f2(r.pathKmPerDay)} | ${f2(r.nightOutPct)} | ${r.alive ? 'yes' : `no (${r.cause})`} | ${r.decisions ? `${r.decisions} (${(100 * (r.rulesAgree ?? 0)).toFixed(0)}%; ${fb || 'none'})` : '–'} |`);
    for (const [label, id, fn, applies] of ROWS) {
      if (!applies(r)) continue;
      const v = fn(r), b = band(id), k = `${label}|${name}`;
      inBand[k] ??= [0, 0]; inBand[k][1]++;
      if (v !== null && v >= b.lo && v <= b.hi) inBand[k][0]++;
    }
  }
  for (const [name, G] of [arms[2], arms[4]]) {
    if (!G) continue;
    const picks: Record<string, number> = {}, rules: Record<string, number> = {};
    for (const r of G.focal) { for (const [k, v] of Object.entries(r.picks)) picks[k] = (picks[k] ?? 0) + v; for (const [k, v] of Object.entries(r.rulesPicks)) rules[k] = (rules[k] ?? 0) + v; }
    const n = Object.values(picks).reduce((a, b) => a + b, 0);
    md.push('', `${name}'s choices by family (the rules' argmax on the same menus): ${Object.keys({ ...picks, ...rules }).sort((a, b) => (picks[b] ?? 0) - (picks[a] ?? 0)).map(k => `${k} ${(100 * (picks[k] ?? 0) / n).toFixed(0)}% (${(100 * (rules[k] ?? 0) / n).toFixed(0)}%)`).join(', ')}.`);
  }
  md.push('', `Deaths in the window: ${arms.filter(a => a[1]).map(([n, a]) => `${n} ${a!.deaths.length}${a!.deaths.length ? ` (${a!.deaths.map(d => d.cause).join(', ')})` : ''}`).join('; ')}.`, '');
}
md.push('## Field rows: focal animals in band', '', '| row (band) | R | A | G | AG | GG |', '|---|---|---|---|---|---|');
for (const [label, id] of ROWS) {
  const b = band(id), cell = (arm: string) => { const v = inBand[`${label}|${arm}`]; return v ? `${v[0]}/${v[1]}` : '–'; };
  md.push(`| ${label} (${b.lo}–${b.hi}) | ${cell('R')} | ${cell('A')} | ${cell('G')} | ${cell('AG')} | ${cell('GG')} |`);
}
// per arm, the mean over focal animals (both seeds) of the readouts, for a compact comparison
md.push('', '## Means over the focal animals (both seeds)', '', '| arm | animals | feed | travel | groom | rest+groom | feed min/d | kcal/d | reserve %/d | km/d (fixes) | night out % | deaths |', '|---|---|---|---|---|---|---|---|---|---|---|---|');
for (const name of ['R', 'A', 'G', 'AG', 'GG']) {
  const rows = means[name];
  if (!rows?.length) continue;
  const m = (fn: (r: Row) => number | null) => { const v = rows.map(fn).filter((x): x is number => x !== null && Number.isFinite(x)); return v.length ? v.reduce((a, c) => a + c, 0) / v.length : NaN; };
  md.push(`| ${name} | ${rows.length} | ${f2(m(r => r.share.feed))} | ${f2(m(r => r.share.travel))} | ${f2(m(r => r.share.groom))} | ${f2(m(r => r.restOrGroom))} | ${m(r => r.feedMinPerDay).toFixed(0)} | ${m(r => r.kcalPerDay).toFixed(0)} | ${m(r => r.reservePctPerDay).toFixed(3)} | ${f2(m(r => r.fixPathKmPerDay))} | ${f2(m(r => r.nightOutPct))} | ${rows.filter(r => !r.alive).length} |`);
}
writeFileSync(join(dir, 'report.md'), md.join('\n') + '\n');
console.log(md.join('\n'));
