// Stage M2 report (docs/staging/em-prereg.md §M2): how each provider chooses on S39's decision points, old and new observation.
// Reads the sample (scripts/em-sample.ts), the probe rows (scripts/em-probes.ts) and the scores (training/decide_ft/em_score.py),
// and writes every table from those files (no number typed by hand).
//
//   pnpm exec tsx scripts/em-report.ts --dir artifacts/em/m2 --providers base,baseline,jev [--out artifacts/em/m2/report]
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { Rec } from './em-sample';

const arg = (k: string, d: string) => { const i = process.argv.indexOf(`--${k}`); return i > 0 ? process.argv[i + 1] : d; };
const dir = resolve(arg('dir', 'artifacts/em/m2')), providers = arg('providers', 'base,baseline,jev').split(','), outBase = resolve(arg('out', join(dir, 'report')));
const lines = (f: string) => existsSync(f) ? readFileSync(f, 'utf8').split('\n').filter(Boolean).map(l => JSON.parse(l)) : [];
const recs: Rec[] = ['s48', 's7'].flatMap(s => lines(join(dir, `${s}.jsonl`)));
const byId = new Map(recs.map(r => [r.id, r]));

function mulberry32(seed: number) { let a = seed >>> 0; return () => { a = (a + 0x6d2b79f5) >>> 0; let t = a; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }
const mean = (xs: number[]) => xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : NaN;
/** 95% bootstrap interval of the mean of `xs` (2,000 resamples, fixed seed). */
function ci(xs: number[], seed = 7): [number, number] {
  if (xs.length < 2) return [NaN, NaN];
  const rnd = mulberry32(seed), m: number[] = [];
  for (let b = 0; b < 2000; b++) { let s = 0; for (let i = 0; i < xs.length; i++) s += xs[Math.floor(rnd() * xs.length)]; m.push(s / xs.length); }
  m.sort((a, b) => a - b);
  return [m[49], m[1949]];
}
const f2 = (v: number) => Number.isFinite(v) ? v.toFixed(2) : '–', f3 = (v: number) => Number.isFinite(v) ? v.toFixed(3) : '–';
const pct = (v: number) => Number.isFinite(v) ? `${(100 * v).toFixed(0)}%` : '–';
const argmax = (p: number[]) => p.reduce((b, v, i) => v > p[b] ? i : b, 0);
const DRAW = (r: Rec) => r.why !== 'kept' && r.why !== 'arrived';

/** Scores of one provider: id → packet → probabilities. */
function scores(file: string): Map<string, Record<string, number[]>> {
  const m = new Map<string, Record<string, number[]>>();
  for (const row of lines(file)) { const e = m.get(row.id) ?? {}; e[row.packet] = row.probs; m.set(row.id, e); }
  return m;
}
const pk = (p: string, obs: 'Old' | 'New' | 'Iso') => `${p === 'jev' ? 'jev' : 'gliner'}${obs}`;

const md: string[] = [`# M2 report (generated by scripts/em-report.ts from ${dir})`, ''];
const json: Record<string, unknown> = { records: recs.length };
md.push(`Sample: ${recs.length} decision points (${recs.filter(DRAW).length} rules draws, ${recs.filter(r => !DRAW(r)).length} kept or arrived), seeds ${[...new Set(recs.map(r => r.seed))].join(', ')}; RG's pick on the model's menu in ${pct(mean(recs.map(r => r.rgIndex >= 0 ? 1 : 0)))}.`, '');

// ---- A. agreement with the rules -------------------------------------------------------------------------------------
const families = [...new Set(recs.flatMap(r => r.options.map(o => o.family)))].sort();
for (const p of providers) {
  const S = new Map<string, Record<string, number[]>>();
  for (const f of p === 'jev' ? ['jev.jsonl'] : ['s48', 's7'].map(s => `${s}.${p}.jsonl`)) for (const [k, v] of scores(join(dir, f))) S.set(k, v);
  const scored = recs.filter(r => S.get(r.id)?.[pk(p, 'Old')] && S.get(r.id)?.[pk(p, 'New')]);
  if (!scored.length) { md.push(`## ${p}: no scores`, ''); continue; }
  const pick = (r: Rec, obs: 'Old' | 'New') => argmax(S.get(r.id)![pk(p, obs)]);
  const res: Record<string, unknown> = { n: scored.length };
  md.push(`## ${p}: agreement with the rules (${scored.length} decision points)`, '',
    '| set | n | old: = RG pick | new: = RG pick | new − old (95% CI) | old: = rules argmax | new: = rules argmax | old c0 | new c0 |', '|---|---|---|---|---|---|---|---|---|');
  for (const [name, set] of [['draws', scored.filter(r => DRAW(r) && r.rgIndex >= 0)], ['kept or arrived', scored.filter(r => !DRAW(r) && r.rgIndex >= 0)], ['all', scored.filter(r => r.rgIndex >= 0)]] as [string, Rec[]][]) {
    const a0 = set.map(r => +(pick(r, 'Old') === r.rgIndex)), a1 = set.map(r => +(pick(r, 'New') === r.rgIndex)), d = set.map((_, i) => a1[i] - a0[i]), c = ci(d);
    const m0 = set.map(r => +(pick(r, 'Old') === r.rulesIndex)), m1 = set.map(r => +(pick(r, 'New') === r.rulesIndex));
    md.push(`| ${name} | ${set.length} | ${pct(mean(a0))} | ${pct(mean(a1))} | ${f3(mean(d))} (${f3(c[0])}, ${f3(c[1])}) | ${pct(mean(m0))} | ${pct(mean(m1))} | ${pct(mean(set.map(r => +(pick(r, 'Old') === 0))))} | ${pct(mean(set.map(r => +(pick(r, 'New') === 0))))} |`);
    res[name] = { n: set.length, old: mean(a0), new: mean(a1), diff: mean(d), ci: c, argmaxOld: mean(m0), argmaxNew: mean(m1) };
  }
  md.push('', `### ${p}: agreement by the rules' family (draws)`, '', '| rules family | n | old agree | new agree | old: picks of the model by family | new: picks of the model by family |', '|---|---|---|---|---|---|');
  const draws = scored.filter(r => DRAW(r) && r.rgIndex >= 0), byFam: Record<string, unknown> = {};
  const dist = (set: Rec[], obs: 'Old' | 'New') => { const n: Record<string, number> = {}; for (const r of set) { const f = r.options[pick(r, obs)].family; n[f] = (n[f] ?? 0) + 1; } return Object.entries(n).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${pct(v / set.length)}`).join(', '); };
  for (const fam of families) {
    const set = draws.filter(r => r.options[r.rgIndex].family === fam);
    if (!set.length) continue;
    const a0 = mean(set.map(r => +(pick(r, 'Old') === r.rgIndex))), a1 = mean(set.map(r => +(pick(r, 'New') === r.rgIndex)));
    md.push(`| ${fam} | ${set.length} | ${pct(a0)} | ${pct(a1)} | ${dist(set, 'Old')} | ${dist(set, 'New')} |`);
    byFam[fam] = { n: set.length, old: a0, new: a1 };
  }
  res.byFamily = byFam;
  // overall pick distribution against the rules' (draws)
  const fdist = (fn: (r: Rec) => string) => { const n: Record<string, number> = {}; for (const r of draws) { const f = fn(r); n[f] = (n[f] ?? 0) + 1; } return n; };
  const rulesD = fdist(r => r.options[r.rgIndex].family), oldD = fdist(r => r.options[pick(r, 'Old')].family), newD = fdist(r => r.options[pick(r, 'New')].family);
  md.push('', `### ${p}: share of choices by family (draws; rules / old / new)`, '', '| family | rules | old | new |', '|---|---|---|---|');
  for (const fam of families) if (rulesD[fam] || oldD[fam] || newD[fam]) md.push(`| ${fam} | ${pct((rulesD[fam] ?? 0) / draws.length)} | ${pct((oldD[fam] ?? 0) / draws.length)} | ${pct((newD[fam] ?? 0) / draws.length)} |`);
  res.share = { rules: rulesD, old: oldD, new: newD, n: draws.length };

  // ---- D. where the model (new observation) differs from the rules: the state that separates the cases --------------
  const VARS: [string, (r: Rec) => number | undefined][] = [
    ['hunger', r => r.context.focal.hunger], ['fatigue (1 − energy)', r => 1 - r.context.focal.energy], ['thirst', r => r.context.focal.thirst], ['loneliness (1 − social)', r => 1 - r.context.focal.social],
    ['deficit', r => r.context.body?.deficit], ['reserves', r => r.context.body?.reserves], ['gut fill', r => r.context.body?.gutFill], ['sleep pressure', r => r.context.body?.sleepPressure],
    ['sleepiness', r => r.context.body?.sleepiness], ['water deficit %', r => r.context.body?.waterDeficitPct], ['heat', r => r.context.body?.heat], ['light', r => r.context.light?.level],
    ['RG pick kcal/h', r => r.context.candidates[r.rgIndex]?.value?.kcalH]];
  md.push('', `### ${p}: where the new-observation choice differs from the rules (draws; cells with ≥ 20 cases)`, '',
    '| rules → model | n | variables most different from the agreeing cases of that rules family: mean disagree / agree (d) |', '|---|---|---|');
  const cells: Record<string, Rec[]> = {};
  for (const r of draws) { const a = r.options[r.rgIndex].family, b = r.options[pick(r, 'New')].family; if (a !== b) (cells[`${a} → ${b}`] ??= []).push(r); }
  const cellOut: Record<string, unknown> = {};
  for (const [cell, set] of Object.entries(cells).sort((a, b) => b[1].length - a[1].length)) {
    if (set.length < 20) continue;
    const fam = cell.split(' → ')[0], agree = draws.filter(r => r.options[r.rgIndex].family === fam && r.options[pick(r, 'New')].family === fam);
    const ds = VARS.map(([name, fn]) => {
      const x = set.map(fn).filter((v): v is number => v !== undefined), y = agree.map(fn).filter((v): v is number => v !== undefined);
      if (x.length < 5 || y.length < 5) return { name, d: NaN, mx: NaN, my: NaN };
      const mx = mean(x), my = mean(y), sd = Math.sqrt((x.reduce((s, v) => s + (v - mx) ** 2, 0) + y.reduce((s, v) => s + (v - my) ** 2, 0)) / Math.max(1, x.length + y.length - 2));
      return { name, d: sd > 0 ? (mx - my) / sd : 0, mx, my };
    }).filter(v => Number.isFinite(v.d)).sort((a, b) => Math.abs(b.d) - Math.abs(a.d)).slice(0, 4);
    md.push(`| ${cell} | ${set.length} | ${ds.map(v => `${v.name} ${f2(v.mx)} / ${f2(v.my)} (${v.d >= 0 ? '+' : ''}${f2(v.d)})`).join('; ')} |`);
    cellOut[cell] = { n: set.length, agreeN: agree.length, top: ds };
  }
  res.cells = cellOut;
  json[p] = res;
  md.push('');
}

// ---- E. state probes --------------------------------------------------------------------------------------------------
const probeRows = lines(join(dir, 'probes.jsonl')) as { id: string; rec: string; probe: string; level: number; levelName: string; target: string[]; options: string[] }[];
if (probeRows.length) {
  md.push('## State probes: probability on the target options at each level (mean over situations); Δ = high − low level (95% CI); share of situations moving the right way', '');
  const probes = [...new Set(probeRows.map(r => r.probe))];
  const pj: Record<string, unknown> = {};
  for (const p of providers) {
    const S = scores(join(dir, `probes.${p}.jsonl`));
    if (!S.size) continue;
    md.push(`### ${p}`, '', '| probe | obs | situations | low | mid | high | Δ (95% CI) | right way | argmax on target low → high |', '|---|---|---|---|---|---|---|---|---|');
    for (const probe of probes) {
      const rows = probeRows.filter(r => r.probe === probe), recIds = [...new Set(rows.map(r => r.rec))];
      for (const obs of ['Old', 'New', 'Iso'] as const) {
        const key = pk(p, obs), mass: number[][] = [[], [], []], top: number[][] = [[], [], []], deltas: number[] = [];
        for (const rid of recIds) {
          const lv = [0, 1, 2].map(l => rows.find(r => r.rec === rid && r.level === l)!);
          const pr = lv.map(r => S.get(r.id)?.[key]);
          if (pr.some(x => !x)) continue;
          const m = pr.map((x, l) => x!.reduce((s, v, i) => s + (lv[l].target.includes(lv[l].options[i]) ? v : 0), 0));
          m.forEach((v, l) => { mass[l].push(v); top[l].push(+lv[l].target.includes(lv[l].options[argmax(pr[l]!)])); });
          deltas.push(m[2] - m[0]);
        }
        if (!deltas.length) continue;
        const c = ci(deltas), right = mean(deltas.map(d => +(d > 0.01))), wrong = mean(deltas.map(d => +(d < -0.01)));
        md.push(`| ${probe} | ${obs.toLowerCase()} | ${deltas.length} | ${f3(mean(mass[0]))} | ${f3(mean(mass[1]))} | ${f3(mean(mass[2]))} | ${f3(mean(deltas))} (${f3(c[0])}, ${f3(c[1])}) | ${pct(right)} (wrong ${pct(wrong)}) | ${pct(mean(top[0]))} → ${pct(mean(top[2]))} |`);
        pj[`${p}:${probe}:${obs}`] = { n: deltas.length, mass: mass.map(mean), delta: mean(deltas), ci: c, right, wrong, top: [mean(top[0]), mean(top[2])] };
      }
    }
    md.push('');
  }
  json.probes = pj;
}
writeFileSync(`${outBase}.md`, md.join('\n') + '\n');
writeFileSync(`${outBase}.json`, JSON.stringify(json, null, 1) + '\n');
console.log(md.join('\n'));
