// Stage R4b (docs/staging/r4b-prereg.md §2, "Reported before training"): the tables of the training data, from the
// assembler's manifest and, for the comparison, from R4's own training file. Nothing here is typed.
//
//   pnpm exec tsx scripts/r4b-data-report.ts [--contexts artifacts/decide-ft/r4b/contexts] [--r4 <R4's contexts dir>] [--md docs/staging/r4b-data.md]
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { kindOfFamily, type R4Rec } from './r4-contexts';
import { DAY_CLASSES, SITUATIONS } from './r4b-assemble';

const arg = (k: string, d: string) => { const i = process.argv.indexOf(`--${k}`); return i > 0 ? process.argv[i + 1] : d; };
const contexts = resolve(arg('contexts', 'artifacts/decide-ft/r4b/contexts')), r4 = arg('r4', '');
type Counts = Record<string, number>;
interface Split { records: number; labelled: number; draws: number; keptOrArrived: number; animals: number; byBase: Counts; byPart: Counts; byDayClass: Counts; byPhase: Counts; daysCovered: number; heatWord: Counts; reservesWord: Counts; waterWord: Counts; rainNow: number; situations: Counts; labelFamily: Counts; labelKind: Counts; drinkLabelsByPhase: Counts; tripLabelsByFruitInReach: Counts; restLabelsByHeatWord: Counts; dayRecordsByHeatWord: Counts }
interface ClassRow { days: number; tMax: number; rainShare: number; cropAgainstYearMean: number; reservesMedian: number; lowShare: number; hotShare: number; firstDay: number; lastDay: number }
const m = JSON.parse(readFileSync(`${contexts}/manifest.json`, 'utf8')) as { commit: string; splits: Record<string, Split>; shortfalls: Record<string, Counts>;
  worlds: { file: string; seed: number; base: string; records: number; worldHash: string; p: number; pool: Record<string, Counts>; census: { days: number; tMax: { min: number; mean: number; max: number }; reservesMedian: { min: number; mean: number; max: number }; alive8: { first: number; last: number }; byClass: Record<string, ClassRow> } }[] };
const md: string[] = ['# R4b: the training and held-out data (generated by scripts/r4b-data-report.ts; do not edit)', '', `Registration: \`docs/staging/r4b-prereg.md\` §2. Assembled at ${m.commit}. Labels: the rules' decisions. Nothing is chosen by its label.`, ''];
const t = (h: string[], rows: (string | number)[][]) => { md.push('', `| ${h.join(' | ')} |`, `| ${h.map(() => '---').join(' | ')} |`, ...rows.map(r => `| ${r.join(' | ')} |`), ''); };
const pct = (v: number) => `${(100 * v).toFixed(1)}%`;

md.push('## The six world-years (rules only; burn-in 6 days, then 365 sampled days)');
t(['world', 'records in the pool', 'animals aged 8 and over, first and last day', 'highest air temperature of a day: lowest, mean, highest (°C)', 'median reserves against the usual store at a day\'s end: lowest, mean, highest', 'world hash'],
  m.worlds.map(w => [`seed ${w.seed}, ${w.base}`, w.records, `${w.census.alive8.first}, ${w.census.alive8.last}`, `${w.census.tMax.min}, ${w.census.tMax.mean}, ${w.census.tMax.max}`, `${pct(w.census.reservesMedian.min)}, ${pct(w.census.reservesMedian.mean)}, ${pct(w.census.reservesMedian.max)}`, w.worldHash]));
md.push('## Day classes from each world\'s census (means over the class\'s days)');
t(['world', 'class', 'days', 'from day, to day', 'highest air temperature (°C)', 'daylight under rain', 'crop index against the year\'s mean', 'median reserves', 'animals 3% or more below their store', 'daylight animal-time "hot"'],
  m.worlds.flatMap(w => DAY_CLASSES.map(c => { const x = w.census.byClass[c]; return [`seed ${w.seed}, ${w.base}`, c, x.days, `${x.firstDay}, ${x.lastDay}`, x.tMax, pct(x.rainShare), x.cropAgainstYearMean, pct(x.reservesMedian), pct(x.lowShare), pct(x.hotShare)]; })));
md.push('## What each world\'s pool holds, by split (records that fit a situation class, and records on days of a class)');
t(['world', 'split', 'records', ...SITUATIONS, ...DAY_CLASSES], m.worlds.flatMap(w => Object.entries(w.pool).map(([s, p]) => [`seed ${w.seed}, ${w.base}`, s, p.records, ...SITUATIONS.map(k => p[k] ?? 0), ...DAY_CLASSES.map(k => p[k] ?? 0)])));
const sf = Object.entries(m.shortfalls);
md.push(sf.length ? `Places a pool could not fill (they went to the middle days of the same world and split): ${sf.map(([k, v]) => `${k.replace('.jsonl', '')} — ${Object.entries(v).map(([p, n]) => `${p} ${n}`).join(', ')}`).join('; ')}.` : 'Every place was filled from its own pool.', '');

const names = Object.keys(m.splits), S = m.splits, row = (label: string, of: (s: Split) => number | string) => [label, ...names.map(n => of(S[n]))];
md.push('## The assembled splits');
t(['', ...names], [row('records', s => s.records), row('labelled (the rules\' decision is on the menu)', s => s.labelled), row('draws', s => s.draws), row('kept or arrived acts', s => s.keptOrArrived), row('animals', s => s.animals), row('world-days covered', s => s.daysCovered),
  row('from W50, from W25', s => `${s.byBase.W50 ?? 0}, ${s.byBase.W25 ?? 0}`), ...[...DAY_CLASSES, ...SITUATIONS].map(p => row(`drawn as: ${p}`, s => s.byPart[p] ?? 0)),
  ...DAY_CLASSES.map(p => row(`falls on a ${p} (however drawn)`, s => s.byDayClass[p] ?? 0)), ...['day', 'dawn', 'dusk', 'night'].map(p => row(`light: ${p}`, s => s.byPhase[p] ?? 0))]);

// R4's training file, by the same words (the comparison of prereg §1)
let old: { records: number; labelled: number; heat: Counts; reserves: Counts; water: Counts; fam: Counts; kind: Counts; drinkPhase: Counts; sit: Counts } | null = null;
if (r4 && existsSync(`${resolve(r4)}/train.jsonl`)) {
  const rows = readFileSync(`${resolve(r4)}/train.jsonl`, 'utf8').split('\n').filter(Boolean).map(l => JSON.parse(l) as R4Rec), lab = rows.filter(r => r.rgIndex >= 0);
  const tally = <T>(xs: T[], of: (x: T) => string) => { const c: Counts = {}; for (const x of xs) { const k = of(x); c[k] = (c[k] ?? 0) + 1; } return c; };
  const parts = (r: R4Rec) => String((r.packet.state as Record<string, unknown>).body ?? '').split('; '), find = (r: R4Rec, words: string[]) => parts(r).find(p => words.includes(p)) ?? 'none';
  const res = (r: R4Rec) => parts(r).find(p => p.startsWith('body reserves '))?.replace('body reserves ', '').replace(/ \(.*\)$/, '') ?? 'none', fam = (r: R4Rec) => r.options[r.rgIndex].family;
  const water = (r: R4Rec) => find(r, ['badly short of water', 'short of water', 'a little short of water', 'well watered']);
  old = { records: rows.length, labelled: lab.length, heat: tally(rows, r => find(r, ['hot', 'warm', 'comfortable temperature', 'chilled', 'cold'])), reserves: tally(rows, res), water: tally(rows, water),
    fam: tally(lab, fam), kind: tally(lab, r => kindOfFamily(fam(r))), drinkPhase: tally(lab.filter(r => fam(r) === 'drink'), r => r.phase),
    sit: { 'hot now': rows.filter(r => find(r, ['hot']) === 'hot').length, 'run down': rows.filter(r => parts(r).some(p => p.startsWith('body reserves ') && p.includes('% below'))).length,
      'short of water, water offered': rows.filter(r => ['short of water', 'badly short of water'].includes(water(r)) && r.options.some(o => o.family === 'drink')).length,
      'food out of sight': rows.filter(r => (r.phase === 'day' || r.phase === 'dawn') && r.options.some(o => o.family === 'food-trip') && !r.options.some(o => o.action === 'forage' && o.targetId >= 100001)).length } };
}
const cols = [...(old ? ['R4 train'] : []), ...names], vals = (ofOld: (o: NonNullable<typeof old>) => number, of: (s: Split) => number) => [...(old ? [ofOld(old)] : []), ...names.map(n => of(S[n]))];
md.push('## The animal\'s state as the packet words it (records)');
const words = (title: string, list: string[], o: (x: NonNullable<typeof old>) => Counts, s: (x: Split) => Counts) => list.map(wd => [`${title}: ${wd}`, ...vals(x => o(x)[wd] ?? 0, x => s(x)[wd] ?? 0)]);
t(['', ...cols], [['records', ...vals(o => o.records, s => s.records)],
  ...words('heat', ['hot', 'warm', 'comfortable temperature', 'chilled', 'cold'], o => o.heat, s => s.heatWord),
  ...words('reserves', ['above my usual store', 'at my usual store', 'a little low', 'run down', 'badly run down', 'nearly gone'], o => o.reserves, s => s.reservesWord),
  ...words('water', ['well watered', 'a little short of water', 'short of water', 'badly short of water'], o => o.water, s => s.waterWord),
  ...SITUATIONS.map(k => [`fits the situation: ${k}`, ...vals(o => o.sit[k] ?? 0, s => s.situations[k] ?? 0)]),
  ['rain falling at the decision', ...(old ? ['–'] : []), ...names.map(n => S[n].rainNow)]]);
md.push('## What the rules decided (labelled records)');
const FAMS = ['feed', 'food-trip', 'drink', 'rest', 'nest', 'social-move', 'travel-home', 'affiliative', 'greet', 'aggression', 'mating', 'care', 'call', 'other'];
const famName: Record<string, string> = { feed: 'feeds where it stands', 'food-trip': 'a trip to a remembered food tree', drink: 'a drink', rest: 'rest or shelter', nest: 'the nest', 'social-move': 'moves with others', 'travel-home': 'heads home' };
t(['', ...cols], [['labelled records', ...vals(o => o.labelled, s => s.labelled)], ...FAMS.map(f => [famName[f] ?? f, ...vals(o => o.fam[f] ?? 0, s => s.labelFamily[f] ?? 0)]),
  ...['feeding', 'travel', 'rest', 'social'].map(k => [`kind: ${k} (share)`, ...[...(old ? [(old.kind[k] ?? 0) / old.labelled] : []), ...names.map(n => (S[n].labelKind[k] ?? 0) / S[n].labelled)].map(v => v.toFixed(3))]),
  ...['day', 'dawn', 'dusk', 'night'].map(p => [`a drink, by ${p}`, ...vals(o => o.drinkPhase[p] ?? 0, s => s.drinkLabelsByPhase[p] ?? 0)]),
  ['a trip to food with no ripe fruit in reach, by day or dawn', ...(old ? ['–'] : []), ...names.map(n => S[n].tripLabelsByFruitInReach['no ripe fruit in reach'] ?? 0)],
  ['a trip to food with ripe fruit in reach (or at dusk or night)', ...(old ? ['–'] : []), ...names.map(n => S[n].tripLabelsByFruitInReach['ripe fruit in reach, or dusk or night'] ?? 0)]]);
md.push('## Heat and rest by day (does the data hold the rules\' answer to heat?)', '', 'Daytime records by the body\'s heat word, and the share of them where the rules rest or shelter.');
t(['heat word', ...names.flatMap(n => [`${n}: daytime records`, `${n}: the rules rest`])], ['hot', 'warm', 'comfortable temperature', 'chilled'].map(wd => [wd, ...names.flatMap(n => { const all = S[n].dayRecordsByHeatWord[wd] ?? 0, rest = S[n].restLabelsByHeatWord[wd] ?? 0; return [all, all ? `${rest} (${(rest / all).toFixed(2)})` : '–']; })]));
const text = md.join('\n').replace(/\n{3,}/g, '\n\n') + '\n';
if (arg('md', '')) writeFileSync(resolve(arg('md', '')), text);
console.log(text);
