// Stage R5 pilot (docs/staging/r5-pilot-prereg.md §7, "Deaths"): why an animal died in some arms and not in others.
// Every arm of a seed continues one burned-in world, so every arm draws from the same random sequence (world.rng,
// xorshift32) and differs only in what each draw is used for. Baseline mortality is one draw per animal at the slow step
// (src/sim/life.ts: death when the draw is below about 1e-6 to 1e-5). This script walks the sequence ahead of the
// burn-in, lists its very small values, and replays every arm (the rules arms by ticking, the kernel arms from their
// receipt logs: no model) to find the tick at which each arm meets each small value and who died there, with the
// animal's health and injury just before. Measurement only.
//
//   pnpm exec tsx scripts/r5-deaths.ts [--dir artifacts/r5/pilot] [--seeds 48,7] [--md docs/staging/r5-pilot-deaths.md]
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { answerWaiting } from '../src/kernel/loop';
import { hazard } from '../src/sim/life';
import { paramsOf } from '../src/sim/params';
import { SLOW_HOURS } from '../src/sim/state';
import { tickWorld } from '../src/simulation';
import type { World } from '../src/types';
import { worldHash } from '../tests/fixtures/golden';
import { focalSet } from './em-loop';
import { ARMS, armWorld, DAY, replayKernel, type ArmResult, type Receipt } from './r5-pilot';

/** One step of the simulation's generator (src/sim/rng.ts random), on the raw 32-bit state. */
const step = (x: number) => { x |= 0; x ^= x << 13; x ^= x >>> 17; x ^= x << 5; return x >>> 0; };
/** A draw below this (as a raw state; 2,000 ÷ 2^32 = 4.7e-7) is listed as very small: under the slow-step death chance of a healthy adult (about 1e-6; each death below prints its own). */
const FATAL = 2000;

if (process.argv[1]?.endsWith('r5-deaths.ts')) {
  const arg = (k: string, d: string) => { const i = process.argv.indexOf(`--${k}`); return i > 0 ? process.argv[i + 1] : d; };
  const dir = resolve(arg('dir', 'artifacts/r5/pilot')), seeds = arg('seeds', '48,7').split(',').map(Number), mdFile = arg('md', '');
  (async () => {
    const md: string[] = ['# R5 pilot: deaths in the window and the shared random sequence (generated by scripts/r5-deaths.ts; do not edit)', '',
      `Every arm of a seed continues the same random sequence. "Very small value": a draw below ${FATAL} ÷ 2^32 (${(FATAL / 2 ** 32).toExponential(1)}). An animal dies at a slow step when its draw is below its death chance for that step, printed with each death.`, ''];
    for (const seed of seeds) {
      const rules = join(dir, `s${seed}`, 'rules.json');
      if (!existsSync(rules)) continue;
      const meta = JSON.parse(readFileSync(rules, 'utf8')) as { burnIn: number; paramsFile: string; burnInHash: string; result: ArmResult };
      const base = JSON.parse(readFileSync(resolve(`artifacts/r5/burnin-${meta.paramsFile.replace(/^.*\//, '').replace(/\.json$/, '')}-s${seed}-d${meta.burnIn}.json`), 'utf8')) as World;
      const focal = new Set(focalSet(base).map(f => f.id)), days = meta.result.days;
      // the fatal values ahead: far enough for five days of any arm (about 300,000 draws)
      const fatal: [number, number][] = [];
      for (let n = 1, x = base.rng >>> 0; n <= 400_000; n++) { x = step(x); if (x < FATAL) fatal.push([n, x]); }
      md.push(`## Seed ${seed} (burn-in hash ${meta.burnInHash})`, '', `Very small values in the next 400,000 draws of the sequence: ${fatal.map(([n, v]) => `draw ${n} (${(v / 2 ** 32).toExponential(1)})`).join(', ') || 'none'}.`, '',
        '| arm | draws in the window | very small value met (day, clock hour; draws in that tick) | deaths in the window (animal, age, focal or not, health and injury the tick before, its death chance at that step, cause, tick) | end hash equals the run\'s |', '|---|---|---|---|---|');
      for (const arm of Object.keys(ARMS)) {
        const out = join(dir, `s${seed}`, `${arm}.json`), rf = join(dir, `s${seed}`, `${arm}.receipts.jsonl`);
        if (!existsSync(out)) continue;
        const run = (JSON.parse(readFileSync(out, 'utf8')) as { result: ArmResult }).result, spec = ARMS[arm], kernelArm = spec.kernel !== 'rules';
        const kernel = kernelArm ? replayKernel(readFileSync(rf, 'utf8').split('\n').filter(Boolean).map(l => JSON.parse(l) as Receipt), { missing: 0, menuDiffers: 0 }) : null;
        const w = armWorld(base, spec), P = paramsOf(w), alive = new Map(w.chimps.filter(c => c.alive).map(c => [c.id, { health: c.health, injury: c.injury, chance: 0 }]));
        let pos = spec.redraw ?? 0, cur = w.rng >>> 0;
        const met: string[] = [], deaths: string[] = [];
        for (let i = 0; i < days * DAY; i++) {
          if (kernelArm) for (const c of w.chimps) c.controller = c.alive && focal.has(c.id) ? 'model' : 'rules';
          for (const c of w.chimps) if (c.alive) alive.set(c.id, { health: c.health, injury: c.injury, chance: 1 - Math.exp(-hazard(c, P, 1 / Math.max(1, w.ageRate)) * (SLOW_HOURS / 24 * Math.max(0, w.ageRate)) / 365.25) });
          tickWorld(w);
          let n = 0;
          while (cur !== (w.rng >>> 0)) { cur = step(cur); n++; if (n > 5_000_000) throw new Error('lost the sequence'); }
          for (const [at] of fatal) if (at > pos && at <= pos + n) met.push(`draw ${at}: day ${Math.floor(i / DAY) + 1}, ${(((i % DAY) / 240 + 6.5) % 24).toFixed(1)} h; ${n} draws`);
          pos += n;
          for (const c of w.chimps) if (!c.alive && alive.has(c.id)) { const b = alive.get(c.id)!; alive.delete(c.id); deaths.push(`${c.name} (${c.age.toFixed(1)} y, ${focal.has(c.id) ? '**focal**' : 'not focal'}, health ${b.health.toFixed(2)}, injury ${b.injury.toFixed(2)}, death chance at that step ${b.chance.toExponential(1)}, ${c.causeOfDeath}, tick ${i})`); }
          if (kernelArm) await answerWaiting(w, c => focal.has(c.id) ? kernel : null);
          if ((w.rng >>> 0) !== cur) throw new Error('the kernel step drew from world.rng');
        }
        md.push(`| ${arm} | ${pos - (spec.redraw ?? 0)} | ${met.join('; ') || 'none'} | ${deaths.join('; ') || 'none'} | ${worldHash(w) === run.endHash ? 'yes' : 'no'} |`);
      }
      md.push('');
    }
    const text = md.join('\n');
    if (mdFile) { writeFileSync(resolve(mdFile), text); console.log(`wrote ${resolve(mdFile)}`); } else console.log(text);
  })().catch(e => { console.error(e); process.exit(1); });
}
